version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root 
    ports:
      - 3306:3306

  spring-boot:
    image: safouane00/achat:1.0
    container_name: springcontainer
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - database

    restart: on-failure  