version: '3'
services:

 mysqldb:
   container_name: mysqldb
   image: mysql:latest
   restart: unless-stopped
   environment:
   - MYSQL_DATABASE=achatdb
   - MYSQL_USER=root
   - MYSQL_PASSWORD=root
   volumes:
   - /home/mysql/data:/var/lib/mysql
 spring_app:
   depends_on:
   - mysqldb
   image: aminafares/achat
   container_name: achat
   restart: on-failure
   ports:
   - "8089:8089"
volumes:
    data: 
   